### ISSUE TITLE
Infografia - Vasquez Reyes Gibran Jesus

### ISSUE THREAD

**Issue by GibranVasquez** [SistemasTecTlaxiaco/actividad-1-infografia-GibranVasquez#1]
https://drive.google.com/file/d/1i2m3hBx7MwGMCsBUhfleBix1xX6MJPcs/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
19 puntos (faltan algunas referencias bibliogaficas)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
